---
# Application Control Module
- hosts: "{{target}}"
  gather_facts: no
  tasks:
  - name: Download 7-Zip
    win_get_url:
       url: https://www.7-zip.org/a/7z1900.exe
       dest: c:\ApplicationControl.exe
  
  - name: Ensure 7-Zip is installed via win_package
    win_package:
       path: c:\ApplicationControl.exe
       state: present
